import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-neutral-700 relative w-196 h-196">
        <Image
          src={"/../public/images/homepage.jpg"}
          width={900}
          height={900}
          alt="Post image"
          className="mix-blend-overlay w-full h-full object-contain"
        />
        <div className="absolute font-sans top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
          <h1 className="text-gray-100 text-center text-4xl font-bold uppercase">
            Welcome to Bit Lords,
          </h1>
          <h1 className="mt-3 text-gray-100 text-center text-3xl font-bold uppercase">
            Opening the door in a new Direction
          </h1>
          <p className="mt-6 text-gray-100 text-center">
            Welcome to the Bit Lords,
            {/* home to a passionate community of global
            educators who believe in the power of technology to transform
            teaching and learning, accelerate innovation and solve tough
            problems in education. */}
          </p>
          {/* <button
            type="button"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-base px-6 py-3.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Extra large
          </button> */}
        </div>
      </div>
      <div>HomePage</div>
      <div>
        <div className="text-black-100 text-center text-4xl font-bold uppercase">
          Logistical Solution
        </div>
        <div className="mt-6 text-black-100 text-center tex-xl">
          We aim to provide advanced supply chain management applications that
          links partners, processes and systems across the supply chain.
        </div>
        <Link href="/LogitsticalSoln">
          <button>See all</button>
        </Link>
        <div className="hidden md:flex">
          <Link href="/LogitsticalSoln/TransportationServices">
            <div class="max-w-sm rounded overflow-hidden shadow-lg m-7">
              <img
                class="w-full"
                src="/images/transportationService.jpg"
                alt=""
              />
              <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">Transportation Service</div>
                <p class="text-gray-700 text-base">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Voluptatibus quia, nulla! Maiores et perferendis eaque,
                  exercitationem praesentium nihil.
                </p>
              </div>
              {/* <div class="px-6 pt-4 pb-2">
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #photography
                </span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #travel
                </span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #winter
                </span>
              </div> */}
            </div>
          </Link>
          <Link href="/LogitsticalSoln/SupplyChainLogistics">
            <div class="max-w-sm rounded overflow-hidden shadow-lg m-7">
              <img
                class="w-full"
                src="/images/SupplyChainLogistics.jpg"
                alt=""
              />
              <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">Supply Chain Logistics</div>
                <p class="text-gray-700 text-base">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Voluptatibus quia, nulla! Maiores et perferendis eaque,
                  exercitationem praesentium nihil.
                </p>
              </div>
              {/* <div class="px-6 pt-4 pb-2">
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #photography
                </span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #travel
                </span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #winter
                </span>
              </div> */}
            </div>
          </Link>
          <Link href="/LogitsticalSoln/FinancialServices">
            <div class="max-w-sm rounded overflow-hidden shadow-lg m-7 ">
              <img class="w-full" src="/images/FinancialSoln.jpg" alt="" />
              <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">Financial Services</div>
                <p class="text-gray-700 text-base">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Voluptatibus quia, nulla! Maiores et perferendis eaque,
                  exercitationem praesentium nihil.
                </p>
              </div>
              {/* <div class="px-6 pt-4 pb-2">
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #photography
                </span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #travel
                </span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #winter
                </span>
              </div> */}
            </div>
          </Link>
          <Link href="/LogitsticalSoln/DigitalSolutions">
            <div class="max-w-sm rounded overflow-hidden shadow-lg m-7">
              <img class="w-full" src="/images/DigitalSoln.jpg" alt="" />
              <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">Digital Solutions</div>
                <p class="text-gray-700 text-base">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Voluptatibus quia, nulla! Maiores et perferendis eaque,
                  exercitationem praesentium nihil.
                </p>
              </div>
              {/* <div class="px-6 pt-4 pb-2">
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #photography
                </span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #travel
                </span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                  #winter
                </span>
              </div> */}
            </div>
          </Link>
        </div>
      </div>
    </>
  );
}
